export const themes = [
  { prefix: 'lenteveld', tokensFile: 'www.lenteveld.nl', url: 'https://www.lenteveld.nl' },
  { prefix: 'barneveld', tokensFile: 'www.barneveld.nl', url: 'https://www.barneveld.nl' },
  { prefix: 'bergen', tokensFile: 'www.bergen-nh.nl', url: 'https://www.bergen-nh.nl' },
  { prefix: 'bloemendaal', tokensFile: 'www.bloemendaal.nl', url: 'https://www.bloemendaal.nl' },
  { prefix: 'bunnik', tokensFile: 'www.bunnik.nl', url: 'https://www.bunnik.nl' },
  { prefix: 'castricum', tokensFile: 'www.castricum.nl', url: 'https://www.castricum.nl' },
  { prefix: 'debilt', tokensFile: 'www.debilt.nl', url: 'https://www.debilt.nl' },
  { prefix: 'dijkenwaard', tokensFile: 'www.dijkenwaard.nl', url: 'https://www.dijkenwaard.nl' },
  { prefix: 'ede', tokensFile: 'www.ede.nl', url: 'https://www.ede.nl' },
  // { prefix: 'ermelo', tokensFile: 'www.ermelo.nl', url: 'https://www.ermelo.nl' },
  // { prefix: 'harderwijk', tokensFile: 'www.harderwijk.nl', url: 'https://www.harderwijk.nl' },
  { prefix: 'heemskerk', tokensFile: 'www.heemskerk.nl', url: 'https://www.heemskerk.nl' },
  { prefix: 'heemstede', tokensFile: 'www.heemstede.nl', url: 'https://www.heemstede.nl' },
  { prefix: 'heiloo', tokensFile: 'www.heiloo.nl', url: 'https://www.heiloo.nl' },
  { prefix: 'houten', tokensFile: 'www.houten.nl', url: 'https://www.houten.nl' },
  { prefix: 'heusden', tokensFile: 'www.heusden.nl', url: 'https://www.heusden.nl' },
  { prefix: 'katwijk', tokensFile: 'www.katwijk.nl', url: 'https://www.katwijk.nl' },
  { prefix: 'medemblik', tokensFile: 'www.medemblik.nl', url: 'https://www.medemblik.nl' },
  { prefix: 'nieuwegein', tokensFile: 'www.nieuwegein.nl', url: 'https://www.nieuwegein.nl' },
  { prefix: 'nissewaard', tokensFile: 'www.nissewaard.nl', url: 'https://www.nissewaard.nl' },
  { prefix: 'rhenen', tokensFile: 'www.rhenen.nl', url: 'https://www.rhenen.nl' },
  { prefix: 'schouwen', tokensFile: 'www.schouwen-duiveland.nl', url: 'https://www.schouwen-duiveland.nl' },
  { prefix: 'soest', tokensFile: 'www.soest.nl', url: 'https://www.soest.nl' },
  { prefix: 'tholen', tokensFile: 'www.tholen.nl', url: 'https://www.tholen.nl' },
  { prefix: 'uitgeest', tokensFile: 'www.uitgeest.nl', url: 'https://www.uitgeest.nl' },
  { prefix: 'veenendaal', tokensFile: 'www.veenendaal.nl', url: 'https://www.veenendaal.nl' },
  { prefix: 'voerendaal', tokensFile: 'www.voerendaal.nl', url: 'https://www.voerendaal.nl' },
  { prefix: 'gemeentewestland', tokensFile: 'www.gemeentewestland.nl', url: 'https://www.gemeentewestland.nl' },
  { prefix: 'wijkbijduurstede', tokensFile: 'www.wijkbijduurstede.nl', url: 'https://www.wijkbijduurstede.nl' },
  { prefix: 'woudenberg', tokensFile: 'www.woudenberg.nl', url: 'https://www.woudenberg.nl' },
  // { prefix: 'zeewolde', tokensFile: 'www.zeewolde.nl', url: 'https://www.zeewolde.nl' },
  { prefix: 'zeist', tokensFile: 'www.zeist.nl', url: 'https://www.zeist.nl' },
];
